package vue;

import classes.CreationProjet;
import classes.RechercherProjet;
import classes.SelectionEquipe;
;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author p1207333
 */


public class ChoixEquipe extends javax.swing.JFrame {

    SelectionEquipe selectEquipe;
    RechercherProjet rechercherProjet;
    int nombreH;
    String idProjetSelectionne;

    /**
     * Creates new form ChoixEquipe
     */
    public ChoixEquipe() {
        initComponents();

        selectEquipe = new SelectionEquipe();
        rechercherProjet = new RechercherProjet();


        Vector v = new Vector<>();
        Vector titres = new Vector();
        titres.add("N° etudiant");
        titres.add("Nom Etudiant");
        titres.add("Nbre jour sur ce projet");
        tableEtudiant.setModel(new DefaultTableModel(selectEquipe.rechercheEtudiant(), titres));
        tableEtudiantSelectionner.setModel(new DefaultTableModel(v, titres));

        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listeDeProjet = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        rechercheProjetT = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        idProjetSelec = new javax.swing.JLabel();
        boutonRecherche = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableEtudiantSelectionner = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableEtudiant = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        validerChoixEquipe = new javax.swing.JButton();
        nomResponsable = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idResponsable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Equipe Projet");

        jButton1.setText("►");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouteEtudiant(evt);
            }
        });

        jButton2.setText("◄");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirerEtudiant(evt);
            }
        });

        jButton3.setText("▼");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectionResponsable(evt);
            }
        });

        jButton4.setText("Retour");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourMenu(evt);
            }
        });

        listeDeProjet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listeDeProjet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                afficheProjetSelectionne(evt);
            }
        });
        jScrollPane3.setViewportView(listeDeProjet);

        jLabel4.setText("Recherche du Projet : ");

        jLabel1.setText("Projet Selectionné :");

        boutonRecherche.setText("recherche");
        boutonRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercheProjet(evt);
            }
        });

        tableEtudiantSelectionner.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane4.setViewportView(tableEtudiantSelectionner);

        tableEtudiant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane5.setViewportView(tableEtudiant);

        jLabel2.setText("Nom du responsable projet :");

        validerChoixEquipe.setText("Valider");
        validerChoixEquipe.setEnabled(false);
        validerChoixEquipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valider(evt);
            }
        });

        jLabel3.setText("Numéro du responsable projet :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jButton2))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idProjetSelec, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jButton3))))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rechercheProjetT, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(boutonRecherche))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(validerChoixEquipe)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rechercheProjetT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonRecherche))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idProjetSelec, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(47, 47, 47)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(nomResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(idResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(validerChoixEquipe)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Permet de fermer la fenetre
     *
     * @param evt
     */
    private void retourMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourMenu

        this.dispose();
    }//GEN-LAST:event_retourMenu
    /**
     * récupère les informations contenue dans le jtextField rechercheProjetT
     * transmet ensuite cet info à la classe rechercheProjet de la classe
     * selectEquipe Une liste est renvoyé et est affiché dans le jtable
     * listeDeProjet
     *
     * @param evt
     */
    private void rechercheProjet(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercheProjet
        String nomProjetRecep = rechercheProjetT.getText();
        if (!nomProjetRecep.isEmpty()) {
            Vector liste = new Vector();

            liste = selectEquipe.rechercheProjet(nomProjetRecep);
            Vector titres = new Vector();
            titres.add("N° de projet");
            titres.add("Nom du projet");
            titres.add("Date fin projet");
            titres.add("Duree projet");
            titres.add("Prix/jour");

            listeDeProjet.setModel(new DefaultTableModel(
                    liste,
                    titres));
        }
    }//GEN-LAST:event_rechercheProjet
    /**
     * récupère l'id du projet selectionné dans la jtable listeProjet puis
     * l'affiche dans le label idProjetSelec Enregistrement du nombre de jour
     * total de travail sur ce projet Si le projet à déja une equipe, alors les
     * bouton sont desactivé, sinon ont les active
     *
     * @param evt
     */
    private void afficheProjetSelectionne(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_afficheProjetSelectionne
        int ligneSelectionne = listeDeProjet.getSelectedRow();
        idProjetSelectionne = listeDeProjet.getValueAt(ligneSelectionne, 0).toString();
        idProjetSelec.setText(idProjetSelectionne);
        nombreH = rechercherProjet.nbreJourTravailleProjet(idProjetSelectionne);
        if (rechercherProjet.aUneEquipe(idProjetSelectionne)) {
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
        } else {
            jButton1.setEnabled(true);
            jButton2.setEnabled(true);
            jButton3.setEnabled(true);
        }
    }//GEN-LAST:event_afficheProjetSelectionne
    /**
     * On récupère les informations de la ligne selectionné dans le jTable
     * tableEtudiant et on les transmet à la jtable tableEtudiantSelectionner
     * avec le nombre de jour affecté
     *
     * @param evt
     */
    private void ajouteEtudiant(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouteEtudiant
        JOptionPane res = null;
        String reponse = null;
        int nombreEntre;
        boolean temp = true;
        Vector v = new Vector();
        int ligneSelectionne = tableEtudiant.getSelectedRow();
        String nomEtudiant = (String) tableEtudiant.getValueAt(ligneSelectionne, 1);
        int idEtudiant = (int) tableEtudiant.getValueAt(ligneSelectionne, 0);
        nombreEntre = nombreH + 1;
        while (nombreEntre > nombreH) {
            reponse = res.showInputDialog(this, "Entrer le nombre de jour travaillé pour Mr "
                    + nomEtudiant, "SAISIE NOMBRE HEURES", javax.swing.JOptionPane.PLAIN_MESSAGE);
            if (reponse != null) {
                try {
                    nombreEntre = Integer.parseInt(reponse);
                    if (nombreEntre > nombreH) {
                        res.showMessageDialog(this, "Il reste " + nombreH + " heures à affecter "
                                + "à ce projet, la valeur que vous avez entré est supérieure. ");
                    }
                } catch (Exception e) {
                    res.showMessageDialog(this, "Vous avez entré un caractère invalide ");
                }
            }
        }
        if (reponse != null) {
            nombreH -= nombreEntre;
            v.add(idEtudiant);
            v.add(nomEtudiant);
            v.add(nombreEntre);
            DefaultTableModel model = (DefaultTableModel) tableEtudiantSelectionner.getModel();
            model.addRow(v);
            tableEtudiantSelectionner.setModel(model);

            DefaultTableModel model1 = (DefaultTableModel) tableEtudiant.getModel();
            model1.removeRow(ligneSelectionne);
            tableEtudiant.setModel(model1);
            jButton2.setEnabled(true);
            if (model1.getRowCount() == 0) {
                jButton1.setEnabled(false);
            }
        }
    }//GEN-LAST:event_ajouteEtudiant
    /**
     * On récupère les informations de la ligne selectionné dans le jTable
     * tableEtudiantSelectionner et on les transmet à la jtable tableEtudiant en
     * retirant le nombre de jour affecté
     *
     * @param evt
     */
    private void retirerEtudiant(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirerEtudiant

        int ligneSelectionne = tableEtudiantSelectionner.getSelectedRow();
        Vector v = new Vector();
        String nomEtudiant = (String) tableEtudiantSelectionner.getValueAt(ligneSelectionne, 1);
        int idEtudiant = (int) tableEtudiantSelectionner.getValueAt(ligneSelectionne, 0);
        int nombre = (int) tableEtudiantSelectionner.getValueAt(ligneSelectionne, 2);
        nombreH += nombre;
        v.add(idEtudiant);
        v.add(nomEtudiant);
        v.add("");

        DefaultTableModel model = (DefaultTableModel) tableEtudiant.getModel();
        model.addRow(v);
        tableEtudiant.setModel(model);

        DefaultTableModel model1 = (DefaultTableModel) tableEtudiantSelectionner.getModel();
        model1.removeRow(ligneSelectionne);
        tableEtudiantSelectionner.setModel(model1);
        if (model1.getRowCount() == 0) {
            jButton2.setEnabled(false);
        }
        nomResponsable.setText("");
        idResponsable.setText("");
        jButton3.setEnabled(false);
        jButton1.setEnabled(true);

    }//GEN-LAST:event_retirerEtudiant
    /**
     * On récupère l'idEtudiant de la ligne selectionné et on l'affiche dans le
     * label idResponsable
     *
     * @param evt
     */
    private void selectionResponsable(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectionResponsable
        int ligneSelectionne = tableEtudiantSelectionner.getSelectedRow();
        String nomEtudiant = (String) tableEtudiantSelectionner.getValueAt(ligneSelectionne, 1);
        int idEtudiant = (int) tableEtudiantSelectionner.getValueAt(ligneSelectionne, 0);
        nomResponsable.setText(nomEtudiant);
        idResponsable.setText(String.valueOf(idEtudiant));
        validerChoixEquipe.setEnabled(true);
    }//GEN-LAST:event_selectionResponsable
    /**
     * Verification du nombre de jour affecté par rapport au nombre de jour
     * total du projet message d'erreur si cela ne corespond pas, transmission
     * des données à la méthode ajoutEquipe de la class CreationProjet
     *
     * @param evt
     */
    private void valider(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valider


        JOptionPane res = null;
        boolean reponse = true;
        if (nombreH != 0) {
            res.showMessageDialog(null, "Il reste " + nombreH + " jour à affecter au projet, merci d'ajouter ou de modifier un autre etudiant.");
        } else {
            CreationProjet creationProjet = new CreationProjet();
            reponse = creationProjet.ajoutEquipe(tableEtudiantSelectionner.getModel(), idResponsable.getText(), idProjetSelec.getText());
            if (reponse) {
                res.showMessageDialog(null, "Equipe enregistrée.");
                this.dispose();

            } else {
                res.showMessageDialog(null, "Veuillez remplir correctement le formulaire.");
            }
        }
    }//GEN-LAST:event_valider

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChoixEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChoixEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChoixEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChoixEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChoixEquipe().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonRecherche;
    private javax.swing.JLabel idProjetSelec;
    private javax.swing.JLabel idResponsable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable listeDeProjet;
    private javax.swing.JLabel nomResponsable;
    private javax.swing.JTextField rechercheProjetT;
    private javax.swing.JTable tableEtudiant;
    private javax.swing.JTable tableEtudiantSelectionner;
    private javax.swing.JButton validerChoixEquipe;
    // End of variables declaration//GEN-END:variables
}
