package vue;

import beans.Client;
import classes.RechercherProjet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author p1207333
 */
public class ConsultationProjet extends javax.swing.JFrame {

    RechercherProjet rechercherProjet;
    Client client;

    /**
     * Creates new form ConsultationProjet
     */
    public ConsultationProjet() {
        initComponents();
        rechercherProjet = new RechercherProjet();
        client = new Client();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultSelectionClient = new javax.swing.JButton();
        consultNomClient = new javax.swing.JLabel();
        consultNumClient = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonRetourMenu = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableAfficheProjet = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEtudiantProjet = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultation Projet");

        consultSelectionClient.setText("Selection du client");
        consultSelectionClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonSelectionClient(evt);
            }
        });

        consultNomClient.setText("LABEL NOM CLIENT");

        consultNumClient.setText("LABEL ID CLIENT");

        jLabel3.setText("Projets du client :");

        jButtonRetourMenu.setText("Retour Menu");
        jButtonRetourMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourMenu(evt);
            }
        });

        jButton1.setText("Retour");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourMenu(evt);
            }
        });

        tableAfficheProjet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "numéro de projet", "numéro de client", "Title 3", "Title 4"
            }
        ));
        tableAfficheProjet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                afficheEtudiantProjet(evt);
            }
        });
        jScrollPane3.setViewportView(tableAfficheProjet);

        tableEtudiantProjet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableEtudiantProjet.setEnabled(false);
        jScrollPane1.setViewportView(tableEtudiantProjet);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(consultSelectionClient)
                        .addGap(18, 18, 18)
                        .addComponent(consultNomClient, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consultNumClient, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(458, 458, 458)
                                .addComponent(jButtonRetourMenu)
                                .addGap(0, 198, Short.MAX_VALUE))
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultSelectionClient)
                    .addComponent(consultNomClient)
                    .addComponent(consultNumClient))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRetourMenu)
                    .addComponent(jButton1))
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Permet de fermer la fenetre
     *
     * @param evt
     */
    private void retourMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourMenu
        this.dispose();
    }//GEN-LAST:event_retourMenu
    /**
     * Ouvre la fenetre rechercheClient puis récupère l'id du client en question
     * afin de l'afficher dans le label consultNumClient fait ensuite appel à la
     * méthode projetClient de la class rechercheProjet pour récupérer la liste
     * des projets de ce client que l'on affiche ensuite dans la jtable
     * tableAfficheProjet
     *
     * @param evt
     */
    private void boutonSelectionClient(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonSelectionClient

        new RechercheClient(this, true, client).setVisible(true);

        consultNumClient.setText(String.valueOf(client.getId_client()));
        Vector vector = new Vector();
        vector = rechercherProjet.projetClient(String.valueOf(client.getId_client()));

        Vector columnNames = new Vector();
        columnNames.add("numéro de projet");
        columnNames.add("Numéro de client");
        columnNames.add("Numéro de l'étudiant responsable");
        columnNames.add("Numéro de convention");
        columnNames.add("Nom du Projet");
        columnNames.add("Durée du projet");
        columnNames.add("Date de fin prévue");
        columnNames.add("prix journée");
        columnNames.add("Cout total du Projet");

        tableAfficheProjet.setModel(new DefaultTableModel(vector, columnNames));
    }//GEN-LAST:event_boutonSelectionClient
    /**
     * récupère l'id du projet selectionné et fait appel à la méthode
     * etudiantDuProjet de la classe rechercherProjet pour récupérer la liste
     * d'étudiant de ce projet
     *
     * @param evt
     */
    private void afficheEtudiantProjet(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_afficheEtudiantProjet
        int ligneSelectionnee = tableAfficheProjet.getSelectedRow();
        int idprojet = (Integer) tableAfficheProjet.getValueAt(ligneSelectionnee, 0);


        Vector columnNames = new Vector();
        columnNames.add("numéro Etudiant");
        columnNames.add("Nom Etudiant");
        columnNames.add("Prenom Etudiant");
        columnNames.add("Date naissance");
        columnNames.add("Adresse");


        tableEtudiantProjet.setModel(new DefaultTableModel(rechercherProjet.etudiantDuProjet(idprojet), columnNames));
    }//GEN-LAST:event_afficheEtudiantProjet

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultationProjet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultationProjet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultationProjet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultationProjet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultationProjet().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel consultNomClient;
    private javax.swing.JLabel consultNumClient;
    private javax.swing.JButton consultSelectionClient;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonRetourMenu;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tableAfficheProjet;
    private javax.swing.JTable tableEtudiantProjet;
    // End of variables declaration//GEN-END:variables
}
