package vue;

import DAO.DAOEtudiant;
import DAO.DAOFactory;
import DAO.DAOProjet;
import classes.ClasseFraisEtudiant;
import java.awt.event.KeyEvent;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author root
 */
public class SaisieFrais extends javax.swing.JDialog {

    Object etudiant;
    StringBuffer date = new StringBuffer();

    /**
     * Creates new form SaisieFrais
     */
    public SaisieFrais(java.awt.Frame parent, boolean modal, Object etuSelec, String mois, int annee) {
        super(parent, modal);
        initComponents();
        String anneeee = String.valueOf(annee);
        labelAnne.setText(anneeee);
        labelMois.setText(mois);
        etudiant = etuSelec;
        boutonValider.setEnabled(false);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datePrerempli = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Retour = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablelisteProjet = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        textFieldJour = new javax.swing.JTextField();
        textFieldDeplacement = new javax.swing.JTextField();
        textFieldSejour = new javax.swing.JTextField();
        textFieldAutres = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        convention = new javax.swing.JLabel();
        boutonValider = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelMois = new javax.swing.JLabel();
        labelAnne = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 393));
        addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                valider(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });

        datePrerempli.setText("Jour");

        jLabel7.setText("Montant déplacement : ");

        jLabel8.setText("Selectionner Projet :");

        jLabel9.setText("Montant par séjour :");

        Retour.setText("Retour");
        Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retour(evt);
            }
        });

        tablelisteProjet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id_projet", "nom_projet", "id_convention"
            }
        ));
        tablelisteProjet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickChoixProjet(evt);
            }
        });
        jScrollPane1.setViewportView(tablelisteProjet);

        jLabel10.setText("Montant autres :");

        textFieldJour.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verifDate(evt);
            }
        });

        textFieldDeplacement.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verifdep(evt);
            }
        });

        textFieldSejour.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verifSej(evt);
            }
        });

        textFieldAutres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verifAutre(evt);
            }
        });

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh(evt);
            }
        });

        jLabel1.setText("Convention selectionnée :");

        boutonValider.setText("Valider");
        boutonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressBoutonValider(evt);
            }
        });

        jLabel3.setText("Mois :");

        jLabel4.setText("Annee :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Retour)
                                .addGap(191, 191, 191)
                                .addComponent(boutonValider))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textFieldAutres, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(textFieldSejour, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(datePrerempli, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textFieldJour, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textFieldDeplacement, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(convention, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelAnne, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(labelMois, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                .addGap(31, 31, 31)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(347, 347, 347))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(labelMois, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(labelAnne, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(convention, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datePrerempli)
                    .addComponent(textFieldJour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textFieldDeplacement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textFieldSejour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(textFieldAutres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Retour)
                    .addComponent(boutonValider))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retour(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retour
        this.dispose();
    }//GEN-LAST:event_retour

    private void clickChoixProjet(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickChoixProjet
        int ligne = tablelisteProjet.getSelectedRow();
        convention.setText((String) tablelisteProjet.getValueAt(ligne, 2));
        verifChamp();
    }//GEN-LAST:event_clickChoixProjet

    private void refresh(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh
        ClasseFraisEtudiant classeFrais = new ClasseFraisEtudiant();
        Vector vectorEtu = classeFrais.recupereListeProjet(etudiant.toString());
        Vector titre = new Vector();
        titre.addElement("idProjet");
        titre.addElement("nomProjet");
        titre.addElement("idConvention");
        DefaultTableModel model = (DefaultTableModel) tablelisteProjet.getModel();
        model.setDataVector(vectorEtu, titre);
        tablelisteProjet.setModel((TableModel) model);
    }//GEN-LAST:event_refresh

    private void valider(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_valider
    }//GEN-LAST:event_valider

    private void verifdep(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verifdep
        char t = evt.getKeyChar();
        if (!Character.isDigit(t)) {
            evt.consume();
        }
        verifChamp();
    }//GEN-LAST:event_verifdep

    private void verifSej(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verifSej
        char t = evt.getKeyChar();
        if (!Character.isDigit(t)) {
            evt.consume();
        }
        verifChamp();
    }//GEN-LAST:event_verifSej

    private void verifAutre(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verifAutre
        char t = evt.getKeyChar();
        if (!Character.isDigit(t)) {
            evt.consume();
        }
        verifChamp();
    }//GEN-LAST:event_verifAutre

    private void verifDate(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verifDate
        char t = evt.getKeyChar();
        String mois = labelMois.getText();
        int longe = date.length();
        if (t == KeyEvent.VK_BACK_SPACE && date.length() != 0) {
            date.deleteCharAt(date.length() - 1);
        } else if (date.length() > 1) {
            evt.consume();
        } else if (!Character.isDigit(t)) {
            evt.consume();
        } else if (("Janvier".equals(mois) || "Mars".equals(mois) || "Mai".equals(mois) || "Juillet".equals(mois)
                || "Août".equals(mois) || "Octobre".equals(mois) || "Décembre".equals(mois))) {
            if (date.length() == 0) {
                if (Character.getNumericValue(t) > 3) {
                    evt.consume();
                } else {
                    date.append(t);
                }
            } else if (date.length() == 1) {
                if (date.charAt(0) == '3' && Character.getNumericValue(t) > 1) {
                    evt.consume();
                } else {
                    date.append(t);
                }
            }

        } else if ((mois.equals("Avril") || mois.equals("Juin") || mois.equals("Septembre") || mois.equals("Novembre"))) {
            if (date.length() == 0) {
                if (Character.getNumericValue(t) > 3) {
                    evt.consume();
                } else {
                    date.append(t);
                }
            } else if (date.length() == 1) {
                if (date.charAt(0) == '3' && Character.getNumericValue(t) > 0) {
                    evt.consume();
                } else {
                    date.append(t);
                }
            }
        } else if (mois.equals("Février") && Character.getNumericValue(t) > 29) {
            if (date.length() == 0) {
                if (Character.getNumericValue(t) > 2) {
                    evt.consume();
                } else {
                    date.append(t);
                }
            } else if (date.length() == 1) {
                if (date.charAt(0) == '2' && Character.getNumericValue(t) > 9) {
                    evt.consume();
                } else {
                    date.append(t);
                }
            }
        }
        verifChamp();
    }//GEN-LAST:event_verifDate

    private void pressBoutonValider(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pressBoutonValider
        ClasseFraisEtudiant classeFrais = new ClasseFraisEtudiant();
        String idprojet = (String) tablelisteProjet.getValueAt(tablelisteProjet.getSelectedRow(), 0);
        JOptionPane res = null;
        try {
            classeFrais.ajoutFrais(idprojet, etudiant.toString(),
                    textFieldJour.getText(), labelMois.getText(),labelAnne.getText(),
                    textFieldDeplacement.getText(),
                    textFieldSejour.getText(), textFieldAutres.getText());
            res.showMessageDialog(this, "Frais enregistré avec succès ");
        } catch (Exception e) {
            res.showMessageDialog(this, "Erreur d'enregistrement ");
        }

    }//GEN-LAST:event_pressBoutonValider

    public void verifChamp() {
        boolean jourFilled = !textFieldJour.getText().isEmpty();
        boolean conventionFilled = !convention.getText().isEmpty();
        boolean autresFilled = !textFieldAutres.getText().isEmpty();
        boolean deplacementFilled = !textFieldDeplacement.getText().isEmpty();
        boolean sejourFilled = !textFieldSejour.getText().isEmpty();

        if (jourFilled && conventionFilled && (autresFilled || deplacementFilled || sejourFilled)) {
            boutonValider.setEnabled(true);
        } else {
            boutonValider.setEnabled(false);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Retour;
    private javax.swing.JButton boutonValider;
    private javax.swing.JLabel convention;
    private javax.swing.JLabel datePrerempli;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAnne;
    private javax.swing.JLabel labelMois;
    private javax.swing.JTable tablelisteProjet;
    private javax.swing.JTextField textFieldAutres;
    private javax.swing.JTextField textFieldDeplacement;
    private javax.swing.JTextField textFieldJour;
    private javax.swing.JTextField textFieldSejour;
    // End of variables declaration//GEN-END:variables
}
